/**
 * Created by web on 2018/7/10.
 */
let imgAll = {};
imgAll.home = [
  /*img*/
  "static/img/1.png",
  "static/img/2.png",
  "static/img/3.png",
  "static/img/4.png",
  "static/img/5.png",
  "static/img/6.png",
  "static/img/7.png",
  "static/img/8.png",
  "static/img/9.png",
  "static/img/10.png",
  "static/img/11.png",
  "static/img/12.png",
  "static/img/13.png",
  "static/img/14.png",
  "static/img/15.png",
  "static/img/16.png",
  "static/img/17.png",
  "static/img/18.png",
  "static/img/19.png",
  "static/img/20.png",
  "static/img/21.png",
  "static/img/22.png",
  "static/img/23.png",
  "static/img/24.png",
  "static/img/25.png",
  "static/img/26.png",
  "static/img/27.png",
  "static/img/28.png",
  "static/img/29.png",
  "static/img/30.png",
  "static/img/31.png",
  "static/img/32.png",
  "static/img/33.png",
  "static/img/34.png",
  "static/img/35.png",
  "static/img/36.png",
  "static/img/37.png",
  "static/img/38.png",
  "static/img/39.png",
  "static/img/40.png",
  "static/img/41.png",
  "static/img/42.png",
  "static/img/43.png",
  "static/img/44.png",
  "static/img/45.png",
  "static/img/46.png",
  "static/img/47.png",
  "static/img/48.png",
  "static/img/49.png",
  "static/img/50.png",
  /*其他*/
  // "static/img/h5_bg.jpg",
  // "static/img/add_love.png",
  // "static/img/btn.gif",
  // "static/img/button.png",
  // "static/img/finger.gif",
  // "static/img/loadImg.png",
  // "static/img/mall_star.png",
  // "static/img/paused.png",
  // "static/img/phone.png",
  // "static/img/pink_ball.png",
  // "static/img/rocket.gif",
  // "static/img/rule.png",
  // "static/img/spot1.png",
  // "static/img/spot2.png",
  // "static/img/star.png",
  // "static/img/video_img.jpg",
  // "static/img/yellow_ball.png",
  //
  // /*num*/
  // "static/num/0.png",
  // "static/num/1.png",
  // "static/num/2.png",
  // "static/num/3.png",
  // "static/num/4.png",
  // "static/num/5.png",
  // "static/num/6.png",
  // "static/num/7.png",
  // "static/num/8.png",
  // "static/num/9.png"
]

module.exports = imgAll;
